# Generated by Django 3.2.12 on 2024-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvExplorer', '0002_auto_20240316_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
